experiment:
  epochs: 300000
  max_turns: 100
  record_period: 200
  run_name: staghunt_with_respawn_8radius_with_sinPosEmb_3agents
model:
  GAMMA: 0.95
  LR: 0.00025
  TAU: 0.001
  agent_vision_radius: 8
  batch_size: 64
  epsilon: 1.0
  epsilon_decay: 0.002
  epsilon_min: 0.05
  layer_size: 250
  memory_size: 1024
  model_update_freq: 4
  n_frames: 1
  n_quantiles: 12
  n_step: 3
  sync_freq: 200
world:
  ascii_map_file: stag_hunt_ascii_map_clean.txt
  beam_cooldown: 3
  beam_length: 3
  beam_radius: 1
  destroyable_health: 3
  freeze_duration: 5
  generation_mode: ascii_map
  height: 11
  interaction_reward: 1.0
  num_agents: 3
  payoff_matrix:
  - - 4
    - 0
  - - 2
    - 2
  resource_density: 0.15
  respawn_delay: 10
  respawn_lag: 10
  taste_reward: 10
  width: 11
