[tool.poetry]
name = "gem"
version = "0.0.0"  # placeholder for the real version, which is retrieved from git tags
description = "A flexible framework for developing reinforcement learning algorithms."
authors = ["Shon Verch <shon.verch@mail.utoronto.ca>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
