[tool.poetry]
name = "gem"
version = "0.1.0"
description = "A flexible framework for developing reinforcement learning algorithms."
authors = ["Shon Verch <shon.verch@mail.utoronto.ca>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
