experiment:
  name: food_trucks
  epochs: 2000
  max_turns: 100
  epsilon_decay: 0.0001

env:
  height: 11
  width: 11
  layers: 1
  channels: 7
  default_object: EmptyObject
  full_mdp: False
  baker_mode: True
  vision: 4

model:
  iqn:
    type: iRainbowModel
    num: 1
    device: cpu
    parameters:
      state_size: [7, 9, 9]
      action_size: 4
      layer_size: 250
      num_frames: 5
      n_step: 3
      BATCH_SIZE: 64
      BUFFER_SIZE: 1024
      LR: 0.00025
      TAU: .001
      GAMMA: 0.99
      N: 12
      sync_freq: 200
      model_update_freq: 4
      epsilon: 0.75

agent:
  agent:
    num: 1
    model: iqn
    vision: 4
    memory_size: 100

entity:
  truck:
    - cuisine: korean
      value: 20
    - cuisine: lebanese
      value: 5
    - cuisine: mexican
      value: -5


save_dir: './data/'
log: False