experiment:
  name: inverse_food_trucks
  epochs: 100000

model:
  type: VisionTransformer
  device: cpu
  parameters:
    state_size: [5, 9, 9]
    action_space: 4
    layer_size: 200
    patch_size: 3
    num_frames: 10
    batch_size: 1024
    num_layers: 4
    LR: .0001

save_dir: './data/'
log: True