experiment:
  name: food_trucks
  epochs: 20000
  max_turns: 100
  epsilon_decay: 0.0001

env:
  height: 11
  width: 11
  layers: 1
  channels: 5
  default_object: EmptyObject
  truck_prefs: [20, 5, -10]
  full_mdp: True
  baker_mode: True
  vision: 5

model:
  iqn:
    type: iRainbowModel
    num: 1
    device: cpu
    parameters:
      state_size: [5, 11, 11]
      action_size: 4
      layer_size: 250
      memory_size: 5
      n_step: 3
      BATCH_SIZE: 64
      BUFFER_SIZE: 1024
      LR: 0.00025
      TAU: .001
      GAMMA: 0.99
      N: 12
      sync_freq: 200
      epsilon: 0.75

agent:
  num: 1
  model: iqn
  vision: 5
  memory_size: 100

save_dir: './data/'
log: True