
experiment:
  name: rpg
  epochs: 4000
  max_turns: 100
  epsilon_decay: 0.0001

env:
  height: 15
  width: 15
  layers: 1
  channels: 3
  default_object: EmptyObject
  full_mdp: False
  tile_size: [16, 16]
  prob:
    item_spawn: 0.15
    item_choice: [0.1, 0.3, 0.4, 0.2] # gem, coin, food, bone

model:
  iqn:
    type: iRainbowModel
    num: 1
    device: cpu
    parameters:
      state_size: [3, 15, 15]
      action_size: 4
      layer_size: 250
      num_frames: 5
      n_step: 3
      BATCH_SIZE: 64
      BUFFER_SIZE: 1024
      LR: 0.00025
      TAU: .001
      GAMMA: 0.99
      N: 12
      sync_freq: 200
      model_update_freq: 4
      epsilon: 0.05

agent:
  agent:
    num: 1
    model: iqn
    num_memories: 3
    vision: 7
    appearance: (0.0, 0.0, 255.0)
    tile_size: (1, 1)
    pov_size: 9
    health: 10
    memory_size: 100

entity:
  Gem:
    start_num: 1
    value: 10
    appearance: (0.0, 255.0, 0.0) # Green
  Coin:
    start_num: 1
    value: 2
    appearance: (255.0, 255.0, 0.0) # Yellow
  Food:
    start_num: 1
    value: 1
    appearance: (255.0, 0.0, 0.0) # Red
  Bone:
    start_num: 1
    value: -4
    appearance: (0, 0, 0) # Black

replay:
  use_sprites: False
  save: True
  replay_frequency: 500
  num_replays: 3
  end_update: True
  epsilon: 0.01
  blit: False
  fps: 2
  turns: 100


root: '/Users/rgelpi/Documents/GitHub/transformers'
log: True