
experiment:
  name: rpg
  epochs: 10000
  max_turns: 100

env:
  dimensions:
    x: 15
    y: 15
    z: 1
    tile_size: (1, 1)
  prob:
    item_spawn: 0.15
    item_choice: (0.1, 0.3, 0.4, 0.2) # gem, coin, food, bone

model:
  agent_cnn:
    type: Model_CNN_LSTM_DQN
    num: 1
    device: cpu
    parameters:
      in_channels: 3
      num_filters: 5
      lr: 0.001
      replay_size: 2048
      in_size: 1450 #650
      hid_size1: 75
      hid_size2: 30
      out_size: 4
      priority_replay: False

      epochs: 1000
      sync_freq: 500
      inepoch_training_freq: 25
      epsilon: 0.99
      gamma: 0.9
      inepoch_batch: 128
      postepoch_batch: 256

agent:
  agent:
    num: 1
    model: agent_cnn
    num_memories: 3
    visual_depth: 4
    appearance: (0.0, 0.0, 255.0)
    tile_size: (1, 1)
    pov_size: 9
    health: 10

entities:
  Gem:
    value: 10
    appearance: (0.0, 255.0, 0.0)
  Coin:
    value: 2
    appearance: (255.0, 255.0, 0.0)
  Food:
    value: 1
    appearance: (255.0, 0.0, 0.0)
  Bone:
    value: -4
    appearance: (0, 0, 0)


save_dir: 'your save dir'