experiment:
  name: cleanup
  epochs: 1
  max_turns: 100
  epsilon_decay: 0.0001

env:
  height: 21
  width: 31
  layers: 3
  default_object: EmptyObject
  full_mdp: False
  vision: 4
  pollution_threshold: 1.0
  initial_apples: 20
  apple_spawn_chance: 0.002
  pollution_spawn_chance: 0.00

model:
  iqn:
    type: iRainbowModel
    parameters:
      action_size: 4
      layer_size: 250
      n_step: 3
      BATCH_SIZE: 64
      BUFFER_SIZE: 1024
      LR: 0.00025
      TAU: .001
      GAMMA: 0.99
      N: 12
      sync_freq: 200
      model_update_freq: 4
      epsilon: 0.01
      device: cpu

agent:
  agent:
    num: 1
    model: iqn
    beam_radius: 3
    rotation: False
    obs:
      channels: 8
      vision: 5
      num_frames: 5
      embeddings: 3

root: '~/Documents/GitHub/agentarium'
log: False