experiment:
  name: cleanup
  epochs: 1
  max_turns: 100
  epsilon_decay: 0.0001

env:
  height: 21
  width: 31
  layers: 3
  channels: 8
  default_object: EmptyObject
  full_mdp: True
  vision: 4
  pollution_threshold: 1.0
  apple_spawn_chance: 0.001
  pollution_spawn_chance: 0.00

agent:
  agent:
    num: 4
    model: iqn
    vision: 4
    memory_size: 100
    appearance: [255, 0, 0, 0, 0, 0, 0, 0]
    beam_radius: 3
    rotation: False

root: '~/GitHub/agentarium'