experiment:
  name: cleanup
  epochs: 2000
  max_turns: 100
  epsilon_decay: 0.0001

env:
  height: 21
  width: 31
  layers: 3
  channels: 8
  default_object: EmptyObject
  full_mdp: False
  vision: 4

agent:
  agent:
    num: 4
    model: iqn
    vision: 4
    memory_size: 100
    appearance: [0, 255, 0, 0, 0, 0, 0, 0]